[colors]

[colors.primary]
background = '#05010C'
foreground = '#FFFFFF'
[colors.normal]
black = "#382952"
red = "#DECCFF"
green = "#DECCFF"
yellow = "#DDCCFF"
blue = "#B59AE6"
magenta = "#B49AE6"
cyan = "#B49AE6"
white = "#DECCFF"

[colors.bright]
black = "#6B578F"
red = "#C3AAF0"
green = "#C2AAF0"
yellow = "#C2AAF0"
blue = "#B59AE6"
magenta = "#B49AE6"
cyan = "#B49AE6"
white = "#C3AAF0"

[colors.cursor]
text = "#C7CAC2"
cursor = "#814DDE"
